apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes auto;
    pid /run/nginx.pid;
    error_log /var/log/nginx/error.log;

    events {
        worker_connections 768;
    }

    http{

        server {
            listen 80 ;
            listen [::]:80 ;

            server_name reto3dmelguizor.online www.reto3dmelguizor.online;

            location / {
                proxy_pass http://wordpress-service;
            }
        }
    }